export const department = [
  { id: 0, name: "Choose Department" },
  { id: 1, name: "Executive Office" },
  { id: 2, name: "General Services Department" },
  { id: 3, name: "Marketing Department" },
  { id: 4, name: "Franchise Department" },
  { id: 5, name: "Management Information System Department" },
  { id: 6, name: "Finance Department" },
  { id: 7, name: "Procurement Department" },
  { id: 8, name: "Human Resource Department" },
  { id: 9, name: "OPSSC Standard Compliance Department" },
  { id: 10, name: "Operations Training & Support Department" },
  { id: 11, name: "Store Operations-Taters Lifestyle Centers" },
  { id: 12, name: "Store Operations Department" },
  { id: 13, name: "TEI HUB" },
  { id: 14, name: "TEI HUB SHELL ORDERS" },
  { id: 15, name: "CSR" },
  { id: 16, name: "Free Lancer" },
  { id: 17, name: "Data Analyst" },
  { id: 18, name: "Business Dev" },
];
