export interface DealModel{
    id: number,
    product_image: string,
    name: string,
    description: string,
    delivery_details: string,
    price: number,
    discounted_price: number,
    uom: string,
    add_details: string,
    status: number,
    category: number,
    num_flavor: number,
    add_remarks: number,
    product_hash: number,
    note: number,
    dateadded: string,
    product_code: string,
    report_status: number,
    
    deal_id: number,
    platform_category_id: number,
}