export { TermsAndConditionModal } from "../modals/bsc-terms-and-condition.modal";
export { ReturnPolicyModal } from "../modals/bsc-return-policy.modal";
export { BSCLogin } from "./bsc-login.page";
export { BscSignUp } from "./bsc-sign-up.page";
export { BscDashboard } from "./bsc-dashboard.page";
export { BSCUser } from "./bsc-user.page";
export { BSCEditUser } from "./bsc-edit-user.page";
export { BSCCreateUser } from "./bsc-create-user.page";
export { BSCCreateGroup } from "./bsc-create-group.page";
